training_sentences = [
"xin chào", "chào bạn", "chào nhé", "chào nha", "chào cậu", "chào ấy", "xin chào bạn", "rất vui được gặp bạn","hello", "hi", "hey", "yo", "alo", "ê", "lâu rồi không gặp", "mừng được gặp lại bạn",
"chào buổi sáng","good morning","buổi sáng tốt lành nha","chúc một buổi sáng vui vẻ","chúc bạn ngày mới tốt đẹp","hello good morning","mong bạn có một ngày năng lượng","chào ngày mới",
"chào buổi chiều","good afternoon","chiều nay bạn ổn không","chúc bạn buổi chiều vui vẻ","chiều tốt lành nha",
"chào buổi tối","good evening","buổi tối vui vẻ nhé","tối nay khỏe không","chúc bạn buổi tối ấm áp","tối an lành nha"
"chúc bạn một ngày tốt lành","chúc một ngày làm việc hiệu quả","mong bạn hôm nay gặp nhiều may mắn","hi vọng ngày hôm nay của bạn tuyệt vời",
"hiiiii","hii bạn iu","chào nè","ê bạn ơi","chào nhaaaa","hello bé iu","hế lôoo ^^","lô lô","alo alo",
]

training_labels = [
"G1","G2","G3","G4","G5","G6","G7","G8","G9","G10","G11","G12","G13","G14","G15","G16",
"G17","G18","G19","G20","G21","G22","G23","G24",
"G25","G26","G27","G28","G29",
"G30","G31","G32","G33","G34","G35",
"G36","G37","G38","G39",
"G40","G41","G42","G43","G44","G45","G46","G47","G48"
]

responses = {
"G1": ["Xin chào! Mình là N6, rất vui được gặp bạn."],
"G2": ["Chào bạn! Mình là N6, rất vui được gặp bạn."],
"G3": ["Chào nhé! Mình là N6, rất vui được gặp bạn."],
"G4": ["Chào nha! Mình là N6, rất vui được gặp bạn."],
"G5": ["Chào cậu! Mình là N6, rất vui được gặp cậu."],
"G6": ["Chào ấy! Mình là N6, rất vui được gặp bạn."],
"G7": ["Xin chào bạn! Mình là N6, rất vui được gặp bạn."],
"G8": ["Rất vui được gặp bạn! Mình là N6, luôn sẵn sàng hỗ trợ bạn."],
"G9": ["Hello! Mình là N6, rất vui được gặp bạn."],
"G10": ["Hi! Mình là N6, rất vui được gặp bạn."],
"G11": ["Hey! Mình là N6, rất vui được gặp bạn."],
"G12": ["Yo! Mình là N6, rất vui được gặp bạn."],
"G13": ["Alo! Mình là N6, rất vui được gặp bạn."],
"G14": ["Ê! Mình là N6, rất vui được gặp bạn."],
"G15": ["Lâu rồi không gặp! Mình là N6, rất vui được gặp lại bạn."],
"G16": ["Mừng được gặp lại bạn! Mình là N6, rất vui khi gặp lại bạn."],
"G17": ["Chào buổi sáng! Mình là N6, chúc bạn một ngày mới tràn đầy năng lượng."],
"G18": ["Good morning! Mình là N6, chúc bạn một ngày thật tốt lành."],
"G19": ["Buổi sáng tốt lành nha! Mình là N6, chúc bạn một ngày tràn đầy niềm vui."],
"G20": ["Chúc một buổi sáng vui vẻ! Mình là N6, hy vọng ngày hôm nay của bạn thật tuyệt."],
"G21": ["Chúc bạn ngày mới tốt đẹp! Mình là N6, luôn sẵn sàng hỗ trợ bạn."],
"G22": ["Hello good morning! Mình là N6, chúc bạn bắt đầu ngày mới thật năng lượng."],
"G23": ["Mong bạn có một ngày năng lượng! Mình là N6, hy vọng mọi việc suôn sẻ."],
"G24": ["Chào ngày mới! Mình là N6, chúc bạn một buổi sáng tuyệt vời."],
"G25": ["Chào buổi chiều! Mình là N6, chúc bạn một buổi chiều thư giãn và vui vẻ."],
"G26": ["Good afternoon! Mình là N6, hy vọng buổi chiều nay của bạn thật tốt lành."],
"G27": ["Chiều nay bạn ổn không? Mình là N6, chúc bạn một buổi chiều dễ chịu."],
"G28": ["Chúc bạn buổi chiều vui vẻ! Mình là N6, hy vọng bạn tận hưởng thời gian còn lại trong ngày."],
"G29": ["Chiều tốt lành nha! Mình là N6, chúc buổi chiều của bạn thật thoải mái."],
"G30": ["Chào buổi tối! Mình là N6, chúc bạn một buổi tối thật thư giãn."],
"G31": ["Good evening! Mình là N6, hy vọng tối nay của bạn thật dễ chịu."],
"G32": ["Buổi tối vui vẻ nhé! Mình là N6, chúc bạn có những giây phút thoải mái."],
"G33": ["Tối nay khỏe không? Mình là N6, mong bạn có một buổi tối an lành."],
"G34": ["Chúc bạn buổi tối ấm áp! Mình là N6, hy vọng tối nay bạn cảm thấy dễ chịu."],
"G35": ["Tối an lành nha! Mình là N6, chúc bạn một buổi tối bình yên."],
"G36": ["Chúc bạn một ngày tốt lành! Mình là N6, hy vọng hôm nay bạn sẽ vui vẻ và thuận lợi."],
"G37": ["Chúc một ngày làm việc hiệu quả! Mình là N6, chúc bạn hoàn thành mọi kế hoạch suôn sẻ."],
"G38": ["Mong bạn hôm nay gặp nhiều may mắn! Mình là N6, hy vọng mọi việc đều thuận lợi với bạn."],
"G39": ["Hi vọng ngày hôm nay của bạn tuyệt vời! Mình là N6, chúc bạn tràn đầy năng lượng và niềm vui."],
"G40": ["Hiiiii! Mình là N6, rất vui được gặp bạn."],
"G41": ["Hii bạn iu! Mình là N6, chào bạn nè."],
"G42": ["Chào nè! Mình là N6, vui được trò chuyện cùng bạn."],
"G43": ["Ê bạn ơi! Mình là N6, rất vui khi gặp bạn."],
"G44": ["Chào nhaaaa! Mình là N6, hy vọng bạn có một ngày tuyệt vời."],
"G45": ["Hello bé iu! Mình là N6, chúc bạn một ngày vui vẻ."],
"G46": ["Hế lôoo ^^! Mình là N6, rất vui được gặp bạn."],
"G47": ["Lô lô! Mình là N6, chào bạn nhé."],
"G48": ["Alo alo! Mình là N6, mình luôn sẵn sàng hỗ trợ bạn."]
}
